apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: spring-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 33065
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-service
  template:
    metadata:
      labels:
        app: spring-service
    spec:
      containers:
        - name: spring-service
          image: us-central1-docker.pkg.dev/proyectosa-415901/docker-repository/maven_microservice_ticket:latest-development
          ports:
            - containerPort: 33065  # Puerto de tu aplicación Spring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-service-ms-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-service-ms-user
  template:
    metadata:
      labels:
        app: spring-service-ms-user
    spec:
      containers:
        - name: spring-service-ms-user
          image: us-central1-docker.pkg.dev/proyectosa-415901/docker-repository/maven_microservice_ticket:latest-development
          ports:
            - containerPort: 33065  # Puerto de tu aplicación Spring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-service-ms-reports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-service-ms-reports
  template:
    metadata:
      labels:
        app: spring-service-ms-reports
    spec:
      containers:
        - name: spring-service-ms-reports
          image: us-central1-docker.pkg.dev/proyectosa-415901/docker-repository/maven_microservice_ticket:latest-development
          ports:
            - containerPort: 33065  # Puerto de tu aplicación Spring
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-service
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-service
  template:
    metadata:
      labels:
        app: mysql-service
    spec:
      containers:
        - name: mysql-service
          image: us-central1-docker.pkg.dev/proyectosa-415901/docker-repository/mysql_microservice:latest-development
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-service
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-service
  template:
    metadata:
      labels:
        app: react-service
    spec:
      containers:
        - name: react-service
          image: us-central1-docker.pkg.dev/proyectosa-415901/docker-repository/node_microservice_frontend:latest-development
          ports:
            - containerPort: 5173

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-ingress-ext
  namespace: default
  annotations:
    kubernetes.io/ingress.global-static-ip-name: dev-static-ip
spec:
  rules:
    - host: dev-enviroment.ticketsys-asd.xyz
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: spring-service
                port:
                  number: 80
  defaultBackend:
    service:
      name: spring-service
      port:
        number: 80
status:
  loadBalancer: {}

          